### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [WellsYC/YCMenuView#3]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before

**Comment by WellsYC** [comment]
Hi, I am not clear about what logo is, but thank you for your approval of my project. I am also honored to get the logo you designed.

**Comment by anharismail** [comment]
Thanks for your response.

The logo that can help to improve your project's visuality and identity, like this [sample](https://github.com/Dsiner/CommenPlayer).

I'll provide it as soon as possible.

**Comment by WellsYC** [comment]
I see. Thanks again.

**Comment by anharismail** [comment]
Hello @WellsYC , this is my logo proposal for your project. This idea comes from pop up menu shape and YC initial.

I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

![ycmenuview ver 1](https://user-images.githubusercontent.com/37614260/47700591-a4c69080-dc49-11e8-9eba-db25fccecf7a.png)

**Comment by WellsYC** [comment]
I am really sorry.My wife have a baby，so i keep busy with things at home.Thank you for your works，i will add your icon to my project. The delay was too long,I hope you can understand.Thank you many much.

**Comment by anharismail** [comment]
Hi @WellsYC , glad to hear that happy news. Hope your baby grows healthy.

If you don't mind, I can help you make a pull request about this logo by myself. Also thanks for your kind responses.

**Comment by WellsYC** [comment]
Thanks，I'm not familiar with how to operate it. Please help me make a pull.

**Comment by WellsYC** [comment]
Please tell me if you need any help from me.

**Comment by anharismail** [comment]
Hi @WellsYC, I've pulled a request about the logo.

I also provide cloud files about it. You can use it as you need.

Here the link: https://drive.google.com/drive/u/1/folders/1t2C1y9r5qV0Xxq9UUHP3JiSLlXuTw3na
